from __future__ import annotations

import csv
import hashlib
import json
import shutil
import sys
import tempfile
from importlib import import_module
from pathlib import Path
from typing import Any

from paperkit import __version__
from paperkit.claims import evaluate_claims, load_claims
from paperkit.config import ProjectConfig, load_yaml
from paperkit.publication import render_claim_table, render_project_metadata


def _json_bytes(value: Any) -> bytes:
    return (json.dumps(value, indent=2, sort_keys=True, ensure_ascii=True) + "\n").encode()


def _write_json(path: Path, value: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(_json_bytes(value))


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    digest.update(path.read_bytes())
    return digest.hexdigest()


def _write_summary_csv(path: Path, results: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.writer(handle, lineterminator="\n")
        writer.writerow(["metric", "value"])
        for key in sorted(results):
            if isinstance(results[key], int | float | str | bool):
                writer.writerow([key, results[key]])


def _write_result_macros(path: Path, results: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = ["% Generated by paperkit. Do not edit."]
    for key in sorted(results):
        value = results[key]
        if isinstance(value, int | float):
            command = "".join(part.capitalize() for part in key.split("_"))
            rendered = f"{value:.12g}" if isinstance(value, float) else str(value)
            lines.append(f"\\newcommand{{\\Result{command}}}{{{rendered}}}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _load_analysis(root: Path, import_name: str) -> Any:
    package_source = str(root / "packages" / "python" / "src")
    if package_source not in sys.path:
        sys.path.insert(0, package_source)
    return import_module(f"{import_name}.analysis")


def _conformance_vectors(analysis: Any) -> dict[str, Any]:
    cases = []
    for options, choices in ((1, 0), (2, 1), (3, 2), (8, 4), (10, 6)):
        result = analysis.expected_distinct_choices(options, choices)
        cases.append(
            {
                "input": {"choices": choices, "options": options},
                "expected": result.as_dict(),
            }
        )
    return {
        "schema_version": 1,
        "operation": "expected_distinct_choices",
        "cases": cases,
        "errors": [
            {"input": {"choices": 1, "options": 0}, "type": "ValueError"},
            {"input": {"choices": -1, "options": 2}, "type": "ValueError"},
        ],
    }


def build(root: Path, output_dir: Path | None = None) -> Path:
    root = root.resolve()
    destination = (output_dir or root / "artifacts").resolve()
    config = ProjectConfig.from_file(root / "project.yml")
    claims = load_claims(root / "research" / "claims.yml")
    analysis = _load_analysis(root, config.python_import_name)
    results = analysis.run_analysis(seed=config.random_seed)
    evaluations = evaluate_claims(results, claims)

    destination.parent.mkdir(parents=True, exist_ok=True)
    staging = Path(tempfile.mkdtemp(prefix="paperkit-", dir=destination.parent))
    try:
        _write_json(staging / "results.json", results)
        _write_json(staging / "claim-results.json", {"claims": evaluations})
        _write_json(
            staging / "conformance" / "expected-distinct.json",
            _conformance_vectors(analysis),
        )
        raw_project = load_yaml(root / "project.yml")
        _write_json(
            staging / "site-data.json",
            {
                "schema_version": 1,
                "initialized": config.initialized,
                "project": raw_project["project"],
                "authors": raw_project["authors"],
                "links": raw_project["links"],
                "licenses": raw_project["licenses"],
                "release": raw_project["release"],
                "packages": raw_project["packages"],
                "results": results,
                "claims": evaluations,
            },
        )
        _write_summary_csv(staging / "data" / "summary.csv", results)
        _write_result_macros(staging / "tables" / "result_macros.tex", results)
        (staging / "tables" / "project_metadata.tex").write_text(
            render_project_metadata(root / "project.yml"), encoding="utf-8"
        )
        (staging / "tables" / "claim_status.tex").write_text(
            render_claim_table(claims), encoding="utf-8"
        )

        files = sorted(path for path in staging.rglob("*") if path.is_file())
        manifest = {
            "schema_version": 1,
            "generator": {"name": "paperkit", "version": __version__},
            "project": {
                "slug": config.slug,
                "title": config.title,
                "version": config.version,
                "packages": {
                    "python": config.python_distribution,
                    "javascript": config.javascript_package,
                },
            },
            "random_seed": config.random_seed,
            "claims": [item["id"] for item in evaluations],
            "all_executable_claims_passed": all(item["passed"] for item in evaluations),
            "files": {
                path.relative_to(staging).as_posix(): _sha256(path)
                for path in files
            },
        }
        _write_json(staging / "manifest.json", manifest)

        backup = destination.with_name(f".{destination.name}.previous")
        if backup.exists():
            shutil.rmtree(backup)
        if destination.exists():
            destination.replace(backup)
        staging.replace(destination)
        if backup.exists():
            shutil.rmtree(backup)
    except Exception:
        shutil.rmtree(staging, ignore_errors=True)
        raise
    return destination
