from __future__ import annotations

from pathlib import Path
from typing import Any

from paperkit.claims import Claim
from paperkit.config import ConfigurationError, load_yaml

LATEX_REPLACEMENTS = {
    "\\": r"\textbackslash{}",
    "&": r"\&",
    "%": r"\%",
    "$": r"\$",
    "#": r"\#",
    "_": r"\_",
    "{": r"\{",
    "}": r"\}",
    "~": r"\textasciitilde{}",
    "^": r"\textasciicircum{}",
}


def latex_escape(value: str) -> str:
    return "".join(LATEX_REPLACEMENTS.get(character, character) for character in value)


def _required_mapping(value: Any, context: str) -> dict[str, Any]:
    if not isinstance(value, dict):
        raise ConfigurationError(f"{context} must be a mapping")
    return value


def _required_text(mapping: dict[str, Any], key: str, context: str) -> str:
    value = mapping.get(key)
    if not isinstance(value, str) or not value.strip():
        raise ConfigurationError(f"{context}.{key} must be a non-empty string")
    return value.strip()


def _newcommand(name: str, value: str) -> str:
    return f"\\newcommand{{\\{name}}}{{{value}}}"


def render_project_metadata(project_path: Path) -> str:
    raw = load_yaml(project_path)
    project = _required_mapping(raw.get("project"), "project")
    authors = raw.get("authors")
    if not isinstance(authors, list) or not authors:
        raise ConfigurationError("authors must be a non-empty list")

    author_parts: list[str] = []
    for index, author_value in enumerate(authors):
        author = _required_mapping(author_value, f"authors[{index}]")
        name = latex_escape(_required_text(author, "name", f"authors[{index}]"))
        affiliations = author.get("affiliations")
        if not isinstance(affiliations, list) or not affiliations:
            raise ConfigurationError(f"authors[{index}].affiliations must be a non-empty list")
        affiliation = latex_escape(str(affiliations[0]))
        author_parts.append(f"{name}\\\\{{\\small {affiliation}}}")

    keywords = project.get("keywords")
    categories = project.get("arxiv_categories")
    if not isinstance(keywords, list) or not isinstance(categories, list):
        raise ConfigurationError("project keywords and arxiv_categories must be lists")

    title = latex_escape(_required_text(project, "title", "project"))
    subtitle = latex_escape(_required_text(project, "subtitle", "project"))
    abstract = latex_escape(_required_text(project, "abstract", "project"))
    rendered_authors = r" \and ".join(author_parts)
    rendered_keywords = latex_escape(", ".join(map(str, keywords)))
    rendered_categories = latex_escape(", ".join(map(str, categories)))
    lines = [
        "% Generated by paperkit. Do not edit.",
        _newcommand("PaperTitle", title),
        _newcommand("PaperSubtitle", subtitle),
        _newcommand("PaperAuthors", rendered_authors),
        _newcommand("PaperAbstract", abstract),
        _newcommand("PaperKeywords", rendered_keywords),
        _newcommand("PaperArxivCategories", rendered_categories),
    ]
    return "\n".join(lines) + "\n"


def render_claim_table(claims: list[Claim]) -> str:
    lines = [
        "% Generated by paperkit. Do not edit.",
        r"\begin{longtable}{@{}p{0.18\linewidth}p{0.18\linewidth}p{0.56\linewidth}@{}}",
        r"\toprule",
        r"Claim & Status & Scope \\",
        r"\midrule",
        r"\endhead",
    ]
    for claim in claims:
        lines.append(
            f"{latex_escape(claim.id)} & {latex_escape(claim.status)} & "
            f"{latex_escape(claim.scope)} \\\\"
        )
    lines.extend([r"\bottomrule", r"\end{longtable}"])
    return "\n".join(lines) + "\n"
